CREATE TABLE IF NOT EXISTS context_sync_state_log (
  log_id CHAR(64) NOT NULL,
  run_id CHAR(64) NOT NULL,
  sequence_no SMALLINT UNSIGNED NOT NULL,
  event_id VARCHAR(191) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  delivery_attempt SMALLINT UNSIGNED NOT NULL,
  triggered_at DATETIME(3) NOT NULL,
  recorded_at DATETIME(3) NOT NULL,
  page_id VARCHAR(191) NOT NULL,
  document_id VARCHAR(191) NULL,
  category VARCHAR(64) NULL,
  state VARCHAR(64) NOT NULL,
  workflow_status VARCHAR(32) NULL,
  validation_status VARCHAR(32) NOT NULL,
  input_fingerprint CHAR(64) NULL,
  source_markdown_sha256 CHAR(64) NULL,
  active_revision_before CHAR(64) NULL,
  candidate_revision_sha256 CHAR(64) NULL,
  parser_version VARCHAR(64) NULL,
  sectioning_version VARCHAR(64) NULL,
  routing_version VARCHAR(64) NULL,
  error_code VARCHAR(128) NULL,
  error_message TEXT NULL,
  retryable BOOLEAN NULL,
  next_action VARCHAR(128) NOT NULL,
  details_json JSON NOT NULL,
  PRIMARY KEY (log_id),
  UNIQUE KEY uk_context_sync_run_sequence (run_id, sequence_no),
  KEY idx_context_sync_page_time (page_id, recorded_at),
  KEY idx_context_sync_document_time (document_id, recorded_at),
  KEY idx_context_sync_state_time (state, recorded_at),
  KEY idx_context_sync_error_time (error_code, recorded_at)
);
